name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Upload requirements file
      uses: actions/upload-artifact@v5
      with:
        name: requirements-file
        path: requirements.txt
  install:
    needs: build
    runs-on: ubuntu-latest  
    steps:
    - name: Download requirements file
      uses: actions/download-artifact@v5
      with:
        name: requirements-file  
    - name: Install dependencies
      run: |
            pip install -r requirements.txt
